# Generated by Django 5.1.8 on 2026-06-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_type_record_record_type_remove_record_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_confidence',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('APPROXIMATE', 'Approximate'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='source_facility',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
