# Generated by Django 5.1.8 on 2026-06-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='connection_token',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Doctor-only QR connection token. Null for patients.', max_length=64, null=True, unique=True),
        ),
    ]
