# Generated by Django 5.1.8 on 2026-06-25 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_type_record_record_type_remove_record_date_and_more'),
        ('sharing', '0005_accessrequest_accessgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessgrant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='patient',
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='scope',
            field=models.CharField(choices=[('NONE', 'No History Access'), ('FULL', 'Full History'), ('SELECTED', 'Selected Records')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_records',
            field=models.ManyToManyField(blank=True, related_name='access_requests', to='records.record'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_scope',
            field=models.CharField(choices=[('FULL', 'Full History'), ('SELECTED', 'Selected Records')], default='FULL', max_length=20),
        ),
        migrations.CreateModel(
            name='CareRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('initiated_by', models.CharField(choices=[('PATIENT_QR', 'Patient QR Scan'), ('DOCTOR_CODE', 'Doctor Code Entry')], max_length=20)),
                ('relationship_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SPECIALIST', 'Specialist'), ('REFERRAL', 'Referral')], default='PRIMARY', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='care_relationship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grant', to='sharing.carerelationship'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='care_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='sharing.carerelationship'),
        ),
        migrations.RemoveField(
            model_name='accessgrant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accessgrant',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='accessgrant',
            name='patient',
        ),
    ]
