# Generated by Django 5.1.8 on 2026-06-25 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Doctor who created this entry, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='visibility',
            field=models.CharField(choices=[('PATIENT_VISIBLE', 'Patient Visible'), ('PROVIDER_ONLY', 'Provider Only')], default='PATIENT_VISIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Doctor who created this entry, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='visibility',
            field=models.CharField(choices=[('PATIENT_VISIBLE', 'Patient Visible'), ('PROVIDER_ONLY', 'Provider Only')], default='PATIENT_VISIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='vitals',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Doctor who created this entry, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitals',
            name='visibility',
            field=models.CharField(choices=[('PATIENT_VISIBLE', 'Patient Visible'), ('PROVIDER_ONLY', 'Provider Only')], default='PATIENT_VISIBLE', max_length=20),
        ),
    ]
